import type { NextPage } from "next";
import { ChangeEvent, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import usePostShortURL from "../hooks/usePostShortURL";

const Home: NextPage = () => {
  const [formData, setFormData] = useState<{
    sourceUrl: string;
    short: string;
  }>({
    sourceUrl: "",
    short: "",
  });

  const isInputValid =
    formData.sourceUrl.startsWith("https://") ||
    formData.sourceUrl.startsWith("http://");

  const { data, isPending, isRejected, isResolved, getShortUrl } =
    usePostShortURL();

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    setFormData(prevState => ({
      ...prevState,
      [event.target.name]: event.target.value,
    }));
  };

  console.log(`Result: https://shortthelong.vercel.app/${data?.slug}`);

  return (
    <div className="max-w-2xl mx-auto">
      <Head>
        <title>Short the Long</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-5xl font-semibold mb-10 text-violet-600">
          Short the Long
        </h1>

        <div className="w-full mb-4">
          <input
            type="text"
            id="sourceUrl"
            name="sourceUrl"
            className="w-full p-2 border rounded-md"
            placeholder="Paste the Long"
            onChange={handleChange}
            disabled={isPending}
          />
        </div>
        <div className="w-full">
          <h3 className="font-semibold mb-2">Custom your Short (optional)</h3>
          <div className="flex items-center w-full">
            <div className="flex items-center border border-gray-200 rounded-md overflow-hidden">
              <span className="p-2 bg-gray-100">
                https://shortthelong.vercel.app/
              </span>
              <input
                type="text"
                id="short"
                name="short"
                className="w-full p-2 border-none"
                placeholder="Your short"
                onChange={handleChange}
                disabled={isPending}
              />
            </div>
            <button
              onClick={() => getShortUrl(formData)}
              className="py-2 px-4 bg-violet-600 ml-auto rounded-md font-medium text-white hover:bg-violet-700 transition-all"
              disabled={!isInputValid || isPending}
            >
              Shorten 🛸
            </button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
